import type { Metadata } from "next";
import { Roboto_Mono, Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";

const robotoMono = Roboto_Mono({
   subsets: ["latin"],
   weight: ["400", "500", "700"],
});

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${robotoMono.className} ${zenKakuGothicNew.className}min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
